# version: '3'
# (Optional) when using custom network
networks:
  lp-apps:
    external: False # create new network with name "<folder_name>-lp-apps"

services:
  pg-db:
    # (Recommended) replace "latest" with specific version
    image: postgres:15
    container_name: pg-db
    environment:
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18
    ports:
      - "5433:5432"
    # (Optional) when using custom network
    networks:
      - lp-apps
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always


  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # TODO change
      PGADMIN_DEFAULT_PASSWORD: postgres # TODO change
      # SCRIPT_NAME: /pgadmin4
    ports:
    - "5050:80"
    networks:
      - lp-apps  
    volumes:
    - pgadmin:/var/lib/pgadmin

  odoo:
    image: odoo:18.0
    container_name: odoo
    ports:
      - "8069:8069"
      # - "7072:7072"
    volumes:
      # - /home/mohsen/Documents/Laplace/Projects/odoo18/addons_ams:/mnt/extra-addons
      # mirror third party custom modules
      # - /home/mohsen/Documents/Laplace/Projects/odoo18/addons_thp/muk_web_theme:/mnt/odoo18/addons_thp/muk_web_theme:ro #
      # - /home/mohsen/Documents/Laplace/Projects/odoo18/addons_thp/lp:/mnt/odoo18/addons_thp/lp:ro #
      - /home/ubuntu/docker-projects/odoo/odoo_e/etc:/etc/odoo # mirror odoo config

      # /var/log/odoo/odoo #shoulde be exist before compose with full permission any user
      # sudo mkdir -p /var/log/odoo/odoo , sudo chmod 777 /var/log/odoo/odoo
      - /var/log/odoo/mep18:/var/log/odoo
      - odoo-web-data:/var/lib/odoo
    environment: # avoid this u should use it in etc/odoo.conf
      - HOST=pg-db # Using the container ID from your output
    #   - USER=odoo18
    #   - PASSWORD=odoo 
    restart: always             # run as a service

    networks:
      - lp-apps


volumes:
  pgadmin:
  db-data:
  odoo-web-data: