# -*- coding: utf-8 -*-
{
    "name": "الطباعة والصباغة",
    "summary": "إدارة أوامر تشغيل ومراحل وماكينات مصانع طباعة وصباغة الأقمشة",
    "version": "19.0.1.6.0",
    "category": "Manufacturing",
    "author": "Thamar",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product", "stock"],
    "data": [
        "security/printing_dyeing_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/stage_type_data.xml",
        "data/machine_data.xml",
        "views/work_order_views.xml",
        "views/operation_views.xml",
        "views/material_issue_views.xml",
        "views/batch_views.xml",
        "views/machine_views.xml",
        "views/configuration_views.xml",
        "views/printing_dyeing_menus.xml",
    ],
    "application": True,
    "installable": True,
}
