# -*- coding: utf-8 -*-
{'name': 'تكاليف مصنع النسيج والصباغة',
 'version': '19.0.1.0.0',
 'author': 'Thamar Dani',
 'category': 'Manufacturing',
 'summary': 'تشغيل الصباغة والتجهيز وتكلفة الساعة حسب الشهر',
 'license': 'LGPL-3',
 'depends': ['base', 'product'],
 'data': ['security/security.xml',
          'security/ir.model.access.csv',
          'data/reference.xml',
          'views/factory_cost_center_views.xml',
          'views/factory_machine_views.xml',
          'views/factory_color_views.xml',
          'views/factory_operation_views.xml',
          'views/factory_cost_category_views.xml',
          'views/factory_fabric_views.xml',
          'views/factory_job_views.xml',
          'views/factory_machine_cost_rate_views.xml',
          'views/factory_dyeing_batch_views.xml',
          'views/factory_menus.xml'],
 'application': True,
 'installable': True,
 'website': 'https://www.thamardani.com',
 'auto_install': False}
