# -*- coding: utf-8 -*-
"""Leave allocation engine for Egyptian labor law compliance.

Handles:
- Dynamic annual leave entitlement computation
- Auto-generation of casual + annual allocations
- Yearly cron for recomputation, carryover, and new allocations
"""
import logging
from datetime import date, datetime

from dateutil.relativedelta import relativedelta

from odoo import api, fields, models, _

_logger = logging.getLogger(__name__)

# ── Constants ──
CASUAL_DAYS = 7
ANNUAL_BASE_STANDARD = 14
ANNUAL_FIRST_YEAR = 8
AGE_BONUS_THRESHOLD = 50        # strictly over this age
AGE_BONUS_DAYS = 9
EXPERIENCE_BONUS_THRESHOLD = 10  # total service years
EXPERIENCE_BONUS_DAYS = 9
HAZARDOUS_BONUS_DAYS = 7


class HrLeaveAllocation(models.Model):
    _inherit = 'hr.leave.allocation'

    # ── Tracking fields ──
    is_auto_generated = fields.Boolean(
        string='Auto-Generated',
        default=False,
        readonly=True,
        help="Indicates this allocation was auto-generated by the leave management system.",
    )
    leave_year = fields.Integer(
        string='Leave Year',
        readonly=True,
        help="The calendar year this allocation applies to.",
    )
    is_opening_balance_adjustment = fields.Boolean(
        string='Opening Balance Adjustment',
        default=False,
        readonly=True,
        help=(
            'Technical allocation that preserves a verified mid-year opening '
            'balance without changing the employee entitlement policy.'
        ),
    )
    opening_balance_id = fields.Many2one(
        'hr.leave.opening.balance',
        string='Opening Balance Source',
        readonly=True,
        index=True,
        ondelete='cascade',
        help='Opening balance record that created this technical adjustment.',
    )
    thamar_carryover_days = fields.Float(
        string='الرصيد المرحّل من السنة السابقة', readonly=True,
        help='Included in the allocation, and immediately available before monthly accrual.',
    )

    # ================================================================
    # PUBLIC API: Entitlement Computation
    # ================================================================

    @api.model
    def _get_hiring_date(self, employee):
        """Return the employee's business hiring date as a ``date``.

        ``hire_date`` is a Datetime field supplied by ``thamar_hr_custom``.
        Leave entitlement must follow that HR hiring date, never the current
        contract/version start date.
        """
        return fields.Datetime.to_datetime(employee.hire_date).date() if employee.hire_date else False

    @api.model
    def _compute_employee_entitlement(self, employee, reference_date=None):
        """Compute the full annual leave entitlement breakdown for an employee.

        Returns a dict with all entitlement details for transparency.

        :param employee: hr.employee or hr.employee.public recordset (single)
        :param reference_date: date to compute against (defaults to today)
        :return: dict with entitlement breakdown
        """
        if reference_date is None:
            reference_date = fields.Date.today()

        # ── Age ──
        age = 0
        if employee.birthday:
            age = relativedelta(reference_date, employee.birthday).years

        # ── Service years ──
        hiring_date = self._get_hiring_date(employee)
        current_service_years = 0.0
        if hiring_date and hiring_date <= reference_date:
            delta = relativedelta(reference_date, hiring_date)
            current_service_years = round(delta.years + delta.months / 12.0, 2)

        external_years = employee.external_experience_years or 0.0
        total_service_years = round(current_service_years + external_years, 2)

        # ── Base annual days ──
        # A hire date is mandatory for an automatic entitlement.  This avoids
        # allocating leave to employee records that have not started work yet.
        employment_year_end = date(reference_date.year, 12, 31)
        employed_in_year = bool(hiring_date and hiring_date <= employment_year_end)
        if not employed_in_year:
            base_days = 0.0
        elif hiring_date.year == reference_date.year:
            # The calendar year of hiring has an 8-day annual base.
            base_days = ANNUAL_FIRST_YEAR
        else:
            # From the following calendar year the annual base is 14 days.
            base_days = ANNUAL_BASE_STANDARD

        # ── Bonuses ──
        # The age and 10-year-service conditions grant one 9-day bonus, not
        # two cumulative bonuses when both conditions are true.
        age_bonus = AGE_BONUS_DAYS if employed_in_year and age > AGE_BONUS_THRESHOLD else 0
        experience_bonus = (
            EXPERIENCE_BONUS_DAYS
            if employed_in_year
            and (total_service_years >= EXPERIENCE_BONUS_THRESHOLD or employee.has_verified_service_bonus)
            and not age_bonus
            else 0
        )
        hazardous_bonus = HAZARDOUS_BONUS_DAYS if employed_in_year and employee.is_hazardous_location else 0

        total_annual = base_days + age_bonus + experience_bonus + hazardous_bonus

        return {
            'age': age,
            'current_service_years': current_service_years,
            'total_service_years': total_service_years,
            'base_days': base_days,
            'age_bonus': age_bonus,
            'experience_bonus': experience_bonus,
            'hazardous_bonus': hazardous_bonus,
            'total_annual': total_annual,
            'casual_days': CASUAL_DAYS if employed_in_year else 0.0,
        }

    @api.model
    def _first_eligible_leave_date(self, employee, year):
        """Return the first date an annual/casual leave can be taken in ``year``.

        The appointment month itself never grants entitlement.  Employees who
        start in December therefore have no eligible leave date in that
        calendar year.
        """
        hiring_date = self._get_hiring_date(employee)
        year_end = date(year, 12, 31)
        if not hiring_date or hiring_date > year_end:
            return False
        if hiring_date.year != year:
            return date(year, 1, 1)
        if hiring_date.month == 12:
            return False
        return date(year, hiring_date.month + 1, 1)

    @api.model
    def _annual_accrual_schedule(self, employee, year, details):
        """Return the annual monthly rate and new entitlement for ``year``.

        A hire earns no annual leave in their hire month.  In the first
        calendar year, the allocation is therefore the monthly rate multiplied
        by the eligible months remaining after that month.
        """
        first_eligible_date = self._first_eligible_leave_date(employee, year)
        monthly_rate = details['total_annual'] / 12.0
        first_eligible_month = first_eligible_date.month if first_eligible_date else False
        hiring_date = self._get_hiring_date(employee)
        if not first_eligible_date:
            eligible_months = 0
        elif hiring_date and hiring_date.year == year:
            # For example: an August hire first earns in September, leaving
            # four eligible months (Sep-Dec) in their first calendar year.
            eligible_months = 13 - first_eligible_month
        else:
            eligible_months = 12
        return {
            'monthly_rate': monthly_rate,
            'first_eligible_month': first_eligible_month,
            'first_eligible_date': first_eligible_date,
            'eligible_months': eligible_months,
            'new_entitlement': round(monthly_rate * eligible_months, 2),
        }

    @api.model
    def _casual_allocation_schedule(self, employee, year, details):
        """Return the casual-leave entitlement available in ``year``.

        In the calendar year of hiring, casual leave follows the same
        proration as annual leave: 7 / 12 × the months after the appointment
        month.  In later years the full 7-day entitlement applies.
        """
        annual_schedule = self._annual_accrual_schedule(employee, year, details)
        monthly_rate = details['casual_days'] / 12.0
        return {
            'monthly_rate': monthly_rate,
            'first_eligible_month': annual_schedule['first_eligible_month'],
            'first_eligible_date': annual_schedule['first_eligible_date'],
            'eligible_months': annual_schedule['eligible_months'],
            'new_entitlement': round(monthly_rate * annual_schedule['eligible_months'], 2),
        }

    @api.model
    def _get_monthly_accrual_policy(self, employee, leave_type, year, details=None):
        """Return the monthly-accrual policy for annual or casual leave.

        Both leave types use the same eligibility date: no entitlement is
        earned during the appointment month.  They intentionally retain
        separate balances and rates, so taking one type can never consume the
        other type's entitlement.
        """
        details = details or self._compute_employee_entitlement(
            employee, date(year, 12, 31),
        )
        if leave_type.is_annual_leave:
            schedule = self._annual_accrual_schedule(employee, year, details)
            full_year_entitlement = details['total_annual']
        elif leave_type.is_casual_leave:
            schedule = self._casual_allocation_schedule(employee, year, details)
            full_year_entitlement = details['casual_days']
        else:
            return False

        return dict(schedule, full_year_entitlement=full_year_entitlement)

    @api.model
    def _get_monthly_accrual_status(
        self, employee, leave_type, year, as_of_date=None, exclude_leave_id=False,
    ):
        """Return the usable balance for a monthly-accrual leave type.

        If an opening balance exists, it is the verified remaining balance on
        its exact cut-off date.  Earlier requests are consequently not
        deducted a second time.  Requests after that date are deducted, while
        the normal monthly rate starts again on the first day of the next
        calendar month.
        """
        as_of_date = fields.Date.to_date(as_of_date or fields.Date.today())
        empty_status = {
            'has_allocation': False,
            'monthly_rate': 0.0,
            'months_accrued': 0,
            'accrual_cap': 0.0,
            'accrued_remaining': 0.0,
            'total_taken': 0.0,
            'full_year_entitlement': 0.0,
            'first_eligible_month': False,
            'opening_balance': 0.0,
            'opening_balance_date': False,
            'remaining_balance': 0.0,
            'approved_taken': 0.0,
        }
        if not leave_type or not leave_type.use_monthly_accrual:
            return empty_status

        allocations = self.sudo().search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('state', '=', 'validate'),
            ('leave_year', '=', year),
            ('date_from', '<=', as_of_date),
            '|', ('date_to', '=', False), ('date_to', '>=', as_of_date),
        ])
        total_allocated = sum(allocations.mapped('number_of_days'))

        details = self._compute_employee_entitlement(employee, date(year, 12, 31))
        policy = self._get_monthly_accrual_policy(employee, leave_type, year, details)
        if not policy:
            return empty_status

        opening_balance = self.env['hr.leave.opening.balance'].sudo().search([
            ('employee_id', '=', employee.id),
            ('leave_type_id', '=', leave_type.id),
            ('balance_year', '=', year),
            ('balance_date', '<=', as_of_date),
        ], limit=1)
        if not total_allocated and not opening_balance:
            return empty_status
        monthly_rate = policy['monthly_rate']
        taken_from = date(year, 1, 1)
        if opening_balance:
            # The stored amount is already net of leave through the exact
            # cut-off date.  The next month's entitlement starts fresh, but
            # any requests in the rest of the cut-off month still reduce it.
            if opening_balance.balance_basis == 'year_remaining':
                monthly_rate = opening_balance._get_source_monthly_rate()
                start_month = policy['first_eligible_month']
                months_accrued = max(0, as_of_date.month - start_month + 1) if start_month else 0
                remaining_months = max(0, policy['eligible_months'] - months_accrued)
                # The full year's unused balance already includes future
                # months. Unlock them, do not add them to the source amount.
                accrual_cap = opening_balance.amount - monthly_rate * remaining_months
            else:
                start_month = min(12, opening_balance.balance_date.month + 1)
                months_accrued = max(0, as_of_date.month - opening_balance.balance_date.month)
                accrual_cap = opening_balance.amount + monthly_rate * months_accrued
            taken_from = opening_balance.balance_date + relativedelta(days=1)
        else:
            start_month = policy['first_eligible_month']
            months_accrued = max(0, as_of_date.month - start_month + 1) if start_month else 0
            accrual_cap = sum(allocations.mapped('thamar_carryover_days')) + monthly_rate * months_accrued

        # Opening balances are backed by a dedicated technical allocation so
        # standard Odoo availability checks remain compatible with verified
        # carried balances.  Do not cap the verified balance at the regular
        # yearly entitlement: that would silently discard valid carryover.
        if not opening_balance:
            accrual_cap = min(round(accrual_cap, 2), total_allocated)
        else:
            accrual_cap = round(accrual_cap, 2)
        leave_domain = [
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('state', 'not in', ('refuse', 'cancel')),
            ('date_from', '>=', datetime.combine(taken_from, datetime.min.time())),
            ('date_from', '<', datetime(year + 1, 1, 1)),
        ]
        excluded_ids = list(self.env.context.get('ignored_leave_ids') or [])
        if exclude_leave_id:
            excluded_ids.append(exclude_leave_id)
        if excluded_ids:
            leave_domain.append(('id', 'not in', excluded_ids))
        leaves = self.env['hr.leave'].sudo().search(leave_domain)
        total_taken = sum(leaves.mapped('number_of_days'))
        remaining_balance = (
            opening_balance.amount
            if opening_balance and opening_balance.balance_basis == 'year_remaining'
            else accrual_cap
        ) - total_taken
        return {
            'has_allocation': True,
            'monthly_rate': round(monthly_rate, 2),
            'months_accrued': months_accrued,
            'accrual_cap': accrual_cap,
            'accrued_remaining': round(max(0.0, accrual_cap - total_taken), 2),
            'total_taken': round(total_taken, 2),
            'full_year_entitlement': policy['full_year_entitlement'],
            'first_eligible_month': start_month,
            'opening_balance': opening_balance.amount if opening_balance else 0.0,
            'opening_balance_date': opening_balance.balance_date if opening_balance else False,
            'remaining_balance': round(remaining_balance, 2),
            'approved_taken': sum(leaves.filtered(lambda leave: leave.state == 'validate').mapped('number_of_days')),
        }

    # ================================================================
    # AUTO-ALLOCATION: Generate allocations for a single employee
    # ================================================================

    @api.model
    def _generate_employee_allocations(self, employee, year=None, carryover_days=0.0):
        """Generate Casual + Annual leave allocations for a given employee and year.

        :param employee: hr.employee record (single)
        :param year: calendar year (defaults to current year)
        :param carryover_days: annual leave days carried over from previous year
        """
        if year is None:
            year = fields.Date.today().year

        hiring_date = self._get_hiring_date(employee)
        if not hiring_date or hiring_date > date(year, 12, 31):
            _logger.info(
                "Skipping leave allocations for %s (%d): no hiring date in %d.",
                employee.name, employee.id, year,
            )
            return

        annual_type = self._get_annual_leave_type(employee.company_id)
        casual_type = self._get_casual_leave_type(employee.company_id)

        if not annual_type and not casual_type:
            _logger.warning(
                "No annual or casual leave types configured for company %s. "
                "Skipping allocation for employee %s.",
                employee.company_id.name, employee.name,
            )
            return

        reference_date = date(year, 12, 31)  # Compute entitlement as of end of year
        details = self._compute_employee_entitlement(employee, reference_date)

        # ── Casual Leave Allocation ──
        snapshot_types = self.env['hr.leave.opening.balance'].sudo().search([
            ('employee_id', '=', employee.id), ('balance_year', '=', year),
            ('balance_basis', '=', 'year_remaining'),
        ]).leave_type_id
        if casual_type and casual_type not in snapshot_types:
            self._create_casual_allocation(employee, casual_type, year, details)

        # ── Annual Leave Allocation ──
        if annual_type and annual_type not in snapshot_types:
            self._create_annual_allocation(employee, annual_type, year, details, carryover_days)

    @api.model
    def _create_casual_allocation(self, employee, leave_type, year, details):
        """Create a fixed-duration casual leave allocation for the year.

        Casual leave: 7 days/year, no carryover.  In the year of appointment
        it is prorated over the months after the appointment month.
        """
        # Check if allocation already exists for this year
        existing = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('is_auto_generated', '=', True),
            ('leave_year', '=', year),
            ('state', '!=', 'refuse'),
        ], limit=1)

        if existing:
            _logger.info(
                "Casual allocation already exists for %s in %d, skipping.",
                employee.name, year,
            )
            return existing

        schedule = self._casual_allocation_schedule(employee, year, details)
        first_eligible_date = schedule['first_eligible_date']
        casual_days = schedule['new_entitlement']
        if not first_eligible_date or not casual_days:
            _logger.info(
                "No casual entitlement remains for %s in %d after the appointment month.",
                employee.name, year,
            )
            return

        notes = (
            "Auto-generated Casual Leave allocation.\n"
            "Year: %d\n"
            "Entitlement: %.2f days\n"
            "Available from: %s\n"
            "Eligible months: %d\n"
            "Rule: 7/12 per eligible month in the hiring year; 7 days in later years; non-carryover, expires Dec 31."
        ) % (year, casual_days, first_eligible_date.isoformat(), schedule['eligible_months'])

        allocation = self.sudo().create({
            'employee_id': employee.id,
            'holiday_status_id': leave_type.id,
            'number_of_days': casual_days,
            'date_from': first_eligible_date,
            'date_to': date(year, 12, 31),
            'notes': notes,
            'allocation_type': 'regular',
            'is_auto_generated': True,
            'leave_year': year,
        })

        # These are system-generated policy allocations, never employee
        # allocation requests.  Explicitly validate them so their availability
        # does not depend on an old database configuration of the leave type.
        if allocation.state == 'confirm':
            allocation._action_validate()

        # Note: allocation_validation_type='no_validation' on the leave type
        # means Odoo auto-approves the allocation on create.

        allocation.message_post(
            body=_(
                "🗓️ <b>Casual Leave Allocation – %(year)d</b><br/>"
                "Entitlement: <b>%(days).2f days</b><br/>"
                "Available from: %(available_from)s<br/>"
                "Eligible months: %(months)d<br/>"
                "Valid until Dec 31, %(year)d<br/>"
                "Non-carryover: expires automatically on Dec 31.",
                year=year,
                days=casual_days,
                available_from=first_eligible_date.isoformat(),
                months=schedule['eligible_months'],
            ),
            message_type='comment',
            subtype_xmlid='mail.mt_note',
        )

        _logger.info(
            "Created casual allocation: %.2f days for %s (%d)",
            casual_days, employee.name, year,
        )
        return allocation

    @api.model
    def _create_annual_allocation(self, employee, leave_type, year, details, carryover_days=0.0):
        """Create the annual allocation and enforce its monthly availability.

        Odoo keeps the allocation as one record; the leave-request constraint
        is the source of truth for the amount actually usable each month.
        """
        # Check if allocation already exists for this year
        existing = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('is_auto_generated', '=', True),
            ('leave_year', '=', year),
            ('state', '!=', 'refuse'),
        ], limit=1)

        if existing:
            _logger.info(
                "Annual allocation already exists for %s in %d, skipping.",
                employee.name, year,
            )
            return existing

        schedule = self._annual_accrual_schedule(employee, year, details)
        total_annual = schedule['new_entitlement']
        total_with_carryover = total_annual + carryover_days

        if not total_with_carryover:
            _logger.info(
                "No annual entitlement remains for %s in %d after the appointment month.",
                employee.name, year,
            )
            return

        # ── Build the computation breakdown for audit trail ──
        notes_lines = [
            "Auto-generated Annual Leave allocation.",
            "Year: %d" % year,
            "",
            "─── Entitlement Breakdown ───",
            "Base annual days: %.1f" % details['base_days'],
            "Monthly accrual rate: %.2f days" % schedule['monthly_rate'],
            "Eligible months this year: %d" % schedule['eligible_months'],
        ]
        if details['age_bonus']:
            notes_lines.append(
                "Age bonus (over 50, age=%d): +%.1f days" % (details['age'], details['age_bonus'])
            )
        if details['experience_bonus']:
            notes_lines.append(
                "Experience bonus (10+ years, total=%.1f): +%.1f days" % (
                    details['total_service_years'], details['experience_bonus']
                )
            )
        if details['hazardous_bonus']:
            notes_lines.append(
                "Hazardous location bonus: +%.1f days" % details['hazardous_bonus']
            )
        notes_lines.append("Total new entitlement: %.1f days" % total_annual)
        if carryover_days:
            notes_lines.append("Carried over from previous year: +%.1f days" % carryover_days)
            notes_lines.append("Grand total: %.1f days" % total_with_carryover)
        notes_lines.append("")
        if leave_type.use_monthly_accrual:
            monthly_rate = schedule['monthly_rate']
            notes_lines.append("Allocation type: Monthly Accrual")
            notes_lines.append("Monthly accrual rate: %.2f days/month" % monthly_rate)
            notes_lines.append("Policy: Balance accrues monthly. Employees cannot")
            notes_lines.append("        take more than their accrued balance.")
        else:
            notes_lines.append("Allocation type: Regular (full balance upfront)")

        notes = "\n".join(notes_lines)

        allocation = self.sudo().create({
            'employee_id': employee.id,
            'holiday_status_id': leave_type.id,
            'number_of_days': total_with_carryover,
            'thamar_carryover_days': carryover_days,
            'date_from': schedule['first_eligible_date'] or date(year, 1, 1),
            'date_to': False,  # No expiry — unlimited carryover
            'notes': notes,
            'allocation_type': 'regular',
            'is_auto_generated': True,
            'leave_year': year,
        })

        # See the equivalent casual-allocation safeguard above.
        if allocation.state == 'confirm':
            allocation._action_validate()

        # Note: allocation_validation_type='no_validation' on the leave type
        # means Odoo auto-approves the allocation on create.

        # ── Post detailed chatter message ──
        body_parts = [
            _("📋 <b>Annual Leave Allocation – %(year)d</b><br/>", year=year),
            _("<b>Base:</b> %(base).1f days<br/>", base=details['base_days']),
        ]
        if details['age_bonus']:
            body_parts.append(
                _("<b>Over-50 age bonus:</b> +%(bonus).1f days (age: %(age)d)<br/>",
                  bonus=details['age_bonus'], age=details['age'])
            )
        if details['experience_bonus']:
            body_parts.append(
                _("<b>Experience 10+ years bonus:</b> +%(bonus).1f days (total service: %(svc).1f yrs)<br/>",
                  bonus=details['experience_bonus'], svc=details['total_service_years'])
            )
        if details['hazardous_bonus']:
            body_parts.append(
                _("<b>Hazardous location bonus:</b> +%(bonus).1f days<br/>",
                  bonus=details['hazardous_bonus'])
            )
        body_parts.append(
            _("<b>New entitlement:</b> %(total).1f days<br/>", total=total_annual)
        )
        if carryover_days:
            body_parts.append(
                _("<b>Carryover:</b> +%(carry).1f days<br/>", carry=carryover_days)
            )
            body_parts.append(
                _("<b>Grand total:</b> %(grand).1f days<br/>", grand=total_with_carryover)
            )
        if leave_type.use_monthly_accrual:
            monthly_rate = schedule['monthly_rate']
            body_parts.append(
                _("<br/>📊 <b>Monthly Accrual Policy Active</b><br/>"
                  "Rate: <b>%(rate).2f days/month</b><br/>"
                  "Employees can only use accrued balance up to the current month.",
                  rate=monthly_rate)
            )

        allocation.message_post(
            body="".join(body_parts),
            message_type='comment',
            subtype_xmlid='mail.mt_note',
        )

        _logger.info(
            "Created annual allocation: %.1f days (%.1f new + %.1f carryover) for %s (%d)",
            total_with_carryover, total_annual, carryover_days, employee.name, year,
        )
        return allocation

    # ================================================================
    # YEARLY CRON JOB
    # ================================================================

    @api.model
    def _cron_yearly_leave_recompute(self):
        """Yearly cron job (Jan 1) to recompute and regenerate all leave allocations.

        Steps:
        1. Determine the new year and previous year
        2. For each active employee:
           a. Calculate remaining annual leave from previous year (carryover)
           b. Generate new casual allocation (7 days, valid current year only)
           c. Generate new annual allocation with carryover balance added
        3. Log all computation details
        """
        today = fields.Date.today()
        new_year = today.year
        prev_year = new_year - 1

        _logger.info(
            "═══ Starting yearly leave recompute for %d ═══", new_year,
        )

        employees = self.env['hr.employee'].search([
            ('active', '=', True),
            ('company_id', '!=', False),
        ])

        _logger.info("Processing %d active employees...", len(employees))

        success_count = 0
        error_count = 0

        for employee in employees:
            try:
                # ── Step 1: Calculate carryover from previous year ──
                carryover = self._compute_annual_carryover(employee, prev_year)

                # ── Step 2: Generate new year allocations ──
                self._generate_employee_allocations(
                    employee,
                    year=new_year,
                    carryover_days=carryover,
                )
                success_count += 1
            except Exception as e:
                error_count += 1
                _logger.error(
                    "Failed to process leave recompute for employee %s (ID: %s): %s",
                    employee.name, employee.id, e,
                )

        _logger.info(
            "═══ Yearly leave recompute completed: %d success, %d errors ═══",
            success_count, error_count,
        )

    @api.model
    def _compute_annual_carryover(self, employee, prev_year):
        """Compute remaining annual leave days to carry over from previous year.

        Carryover is unlimited (per user specification).

        :param employee: hr.employee record
        :param prev_year: the previous calendar year
        :return: float — number of days to carry over
        """
        annual_type = self._get_annual_leave_type(employee.company_id)
        if not annual_type:
            return 0.0

        opening = self.env['hr.leave.opening.balance'].sudo().search([
            ('employee_id', '=', employee.id), ('leave_type_id', '=', annual_type.id),
            ('balance_year', '=', prev_year), ('balance_basis', '=', 'year_remaining'),
        ], limit=1)
        if opening:
            status = self._get_monthly_accrual_status(
                employee, annual_type, prev_year, date(prev_year, 12, 31),
            )
            return status['remaining_balance']

        # Find all approved annual allocations for the previous year
        prev_allocations = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', annual_type.id),
            ('state', '=', 'validate'),
            ('leave_year', '=', prev_year),
        ])

        if not prev_allocations:
            # Also check for allocations without leave_year (legacy or manually created)
            prev_allocations = self.search([
                ('employee_id', '=', employee.id),
                ('holiday_status_id', '=', annual_type.id),
                ('state', '=', 'validate'),
                ('date_from', '>=', date(prev_year, 1, 1)),
                ('date_from', '<=', date(prev_year, 12, 31)),
                ('leave_year', '=', False),
            ])

        if not prev_allocations:
            return 0.0

        # Get consumed leaves data for the previous year
        total_allocated = sum(prev_allocations.mapped('number_of_days'))
        target_date = date(prev_year, 12, 31)

        try:
            consumed_data = employee._get_consumed_leaves(annual_type, target_date)[0]
            total_taken = 0.0
            for alloc, data in consumed_data[employee][annual_type].items():
                if alloc in prev_allocations:
                    total_taken += data.get('leaves_taken', 0.0)
        except Exception as e:
            _logger.warning(
                "Error computing consumed leaves for %s in %d: %s. "
                "Falling back to simple allocation count.",
                employee.name, prev_year, e,
            )
            # Fallback: count approved leaves manually
            leaves = self.env['hr.leave'].search([
                ('employee_id', '=', employee.id),
                ('holiday_status_id', '=', annual_type.id),
                ('state', '=', 'validate'),
                ('date_from', '>=', fields.Datetime.to_datetime(date(prev_year, 1, 1))),
                ('date_to', '<=', fields.Datetime.to_datetime(date(prev_year, 12, 31))),
            ])
            total_taken = sum(leaves.mapped('number_of_days'))

        remaining = max(0.0, total_allocated - abs(total_taken))

        _logger.info(
            "Annual carryover for %s from %d: allocated=%.1f, taken=%.1f, remaining=%.1f",
            employee.name, prev_year, total_allocated, abs(total_taken), remaining,
        )

        return remaining

    # ================================================================
    # HELPER METHODS
    # ================================================================

    @api.model
    def _get_annual_leave_type(self, company=None):
        """Find the leave type marked as Annual Leave."""
        domain = [('is_annual_leave', '=', True)]
        if company:
            domain.append(('company_id', 'in', [company.id, False]))
        return self.env['hr.leave.type'].search(domain, limit=1)

    @api.model
    def _get_casual_leave_type(self, company=None):
        """Find the leave type marked as Casual Leave."""
        domain = [('is_casual_leave', '=', True)]
        if company:
            domain.append(('company_id', 'in', [company.id, False]))
        return self.env['hr.leave.type'].search(domain, limit=1)
